"""add_project_recommendation_tables_and_update_fields

Revision ID: 79b555473a7e
Revises: a292ef2bbc63
Create Date: 2025-10-29 19:40:58.424645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '79b555473a7e'
down_revision: Union[str, None] = 'a292ef2bbc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_embeddings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('required_experience_level', sa.Integer(), nullable=False),
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('embedding_model', sa.String(length=50), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('recommendation_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('recommended_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.add_column('freelancer_embeddings', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('availability_status', sa.String(length=20), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('freelancer_embeddings', sa.Column('experience_level', sa.Integer(), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('total_projects', sa.Integer(), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('embedding_model', sa.String(length=50), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('embedding_version', sa.String(length=20), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('data_quality_score', sa.Float(), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('freelancer_embeddings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('freelancer_embeddings', 'bio_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.alter_column('freelancer_embeddings', 'past_project_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.alter_column('freelancer_embeddings', 'success_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('freelancer_embeddings', 'client_satisfaction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('freelancer_embeddings', 'communication_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('freelancer_embeddings', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('freelancer_embeddings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freelancer_embeddings', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('freelancer_embeddings', 'hourly_rate',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('freelancer_embeddings', 'communication_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('freelancer_embeddings', 'client_satisfaction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('freelancer_embeddings', 'success_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('freelancer_embeddings', 'past_project_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.alter_column('freelancer_embeddings', 'bio_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.drop_column('freelancer_embeddings', 'created_at')
    op.drop_column('freelancer_embeddings', 'meta_info')
    op.drop_column('freelancer_embeddings', 'data_quality_score')
    op.drop_column('freelancer_embeddings', 'embedding_version')
    op.drop_column('freelancer_embeddings', 'embedding_model')
    op.drop_column('freelancer_embeddings', 'total_projects')
    op.drop_column('freelancer_embeddings', 'experience_level')
    op.drop_column('freelancer_embeddings', 'location')
    op.drop_column('freelancer_embeddings', 'availability_status')
    op.drop_column('freelancer_embeddings', 'skills')
    op.drop_table('recommendation_logs')
    op.drop_table('project_embeddings')
    # ### end Alembic commands ###
