"""update_vector_dimensions_to_1536

Revision ID: 8a7a84cac817
Revises: 79b555473a7e
Create Date: 2025-10-29 19:51:48.719175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8a7a84cac817'
down_revision: Union[str, None] = '79b555473a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freelancer_embeddings', 'bio_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.alter_column('freelancer_embeddings', 'past_project_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.alter_column('project_embeddings', 'project_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_embeddings', 'project_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=False)
    op.alter_column('freelancer_embeddings', 'past_project_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.alter_column('freelancer_embeddings', 'bio_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###
