"""Create freelancer_embeddings table

Revision ID: a292ef2bbc63
Revises: 
Create Date: 2025-10-28 17:28:52.219494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a292ef2bbc63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer_embeddings',
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('bio_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('past_project_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('client_satisfaction', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('freelancer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freelancer_embeddings')
    # ### end Alembic commands ###
